### ISSUE TITLE
Improve author's name parsing

### ISSUE THREAD

**Issue by xuanxu** [xuanxu/theoj#4]
Make the code accept [the same keys as Inara](https://github.com/openjournals/inara/blob/main/docs/names.md):

```yaml
authors:
  - name: John Doe
    affiliation: '1'
  - given-names: Ludwig
    dropping-particle: van
    surname: Beethoven
    affiliation: '3'
  # not recommended, but common aliases can be used for name parts.
  - given: Louis
    non-dropping-particle: de
    family: Broglie
    affiliation: '4'
```

``` yaml
authors:
  - name:
      given-names: Kari
      surname: Nordmann
  - name:
      literal: 立花 瀧
      given-names: 瀧
      surname: 立花
```
